version: 0.0

os: linux

files:
  - source: target/myawscdplanet-0.0.1-SNAPSHOT.jar
    destination: /var/www/html/

hooks:
  BeforeInstall:
    - location: scripts/install_dependencies
      timeout: 300
      runas: root
