version: 0.2
 
phases:
  install:
    runtime-versions:
      java: corretto17
  build:
    commands:
      - echo Build started on `date`
      - mvn clean install 
artifacts:
  discard-paths: yes  # yamllint disable-line rule:truthy
  files:
    - target/*
    - scripts/*
    - appspec.yml
